# default.yml controls global settings and policies/reports that run on all hosts ("All fleets").

labels:
  - path ./lib/all/labels/global-label.yml
policies:
reports:
agent_options:
controls:
org_settings:
  fleet_desktop:
    transparency_url: https://catoftheday.com
  host_expiry_settings:
    host_expiry_enabled: true
    host_expiry_window: 30
  server_settings:
    server_url: $FLEET_URL
  org_info:
    org_name: DTKB
  webhook_settings:
    activities_webhook:
      enable_activities_webhook: true
      destination_url: https://webhook.site/ef6be426-73e7-42c2-8889-f211badc5e78
  secrets:
    - secret: "$FLEET_GLOBAL_ENROLL_SECRET"
